### ISSUE TITLE
Grappling flow breaks CanSwallow requirements

### ISSUE THREAD

**Issue by Wh0Kn0w5** [pileofwolves/finmer#22]
As per trello card https://trello.com/c/Mvb5zljp/125-content-fix-being-able-to-eat-large-characters, Characters larger than the player's size are apparently able to be consumed. This was proven accurate on testing done on both the Foxtaur and Direwolf. 

Now, on observations with both aforementioned characters, there was something odd noted. Namely the amount of swallow attempts was related to the size of the character. Assuming on the scale of sizes, with Tiny, Small, Medium, Large and Huge, those values correspond to integers of 1 through 5. Now, if we're assuming the player character is a size of 3, then the Foxtaur is 4 and Direwolf is 5.

On playing with devouring these characters, it took 4 swallow checks to consume the foxtaur and 5 to devour the direwolf. In relation, when attempting to devour the player, it took only 2 checks for the Foxtaur to succeed, and only one for the Direwolf. Thereby, it seems like the size of the character being devoured/devouring is related to the combat swallow check, but not the can or cannot be swallowed aspect that you're looking for.

So, Perhaps an investigation into how the combat swallow call is generated can provide the resolve for this issue.

**Comment by Wh0Kn0w5** [comment]
Actually, I suppose it warrants asking the question.

Should there be just a special message with trying to scarf down too big prey, or should the "Swallow" button just not show if the other character is larger than the player?

**Comment by pileofwolves** [comment]
Thanks for the report!

Ordinarily this is handled by `SceneCombat2.GetViablePreyTargets`. It only returns characters for whom `CanSwallow()` returned true, and that depends on a size check. Hence, the normal Swallow button doesn't appear when fighting the foxtaur or the dire wolf, as expected. However it looks like this doesn't stop the Grapple flow, which then presents a Swallow button anyway - that's a bug.

Your observation that larger creatures require fewer successful swallow checks to win a contest is correct and intentional; see `CombatLogic.PerformVore` for the exact calculations. In short, for every level of size difference between pred and prey, the pred has to win one fewer round, and the inverse if the pred is smaller.

I think it'd be best if the player (or any NPC, for that matter) is not able to initiate a grapple with a larger character in the first place. The same goes for the Reverse option, then, since it has the same effect. This will require a bunch of new plumbing: the `Character` class will need a `CanGrapple` function, which is to be used by a new `SceneCombat2.GetViableGrappleTargets`, which should in turn be used by `ShowUIDefault` and `HandlePlayerInputDefault` to present the buttons only when there is a valid (same-size or smaller) target.

**Comment by pileofwolves** [comment]
Not sure what the best user experience would be, actually. Simply not showing the button is by far easiest, of course, but if it's not tutorialized properly a player might be confused why the option appears sometimes but not always.

**Comment by Wh0Kn0w5** [comment]
Be sure to update the Trello board as well, for all of us watching it too :)
