### ISSUE TITLE
Autovore prey raises assert with ally kills

### ISSUE THREAD

**Issue by Wh0Kn0w5** [pileofwolves/finmer#37]
Combat scenarios where player fights alongside allies against enemies with "Swallowed when killed" enabled will throw a light exception when the ally characters deliver a final blow to the enemy in question. 

## Assertion call stack:

```
at Finmer.Gameplay.Combat.CombatSession.NotifyParticipantKilled(Participant killer, Participant victim) in C:\plokij\Finmer Custom\finmer\Finmer.Game\Gameplay\Combat\CombatSession.cs:line 208
at Finmer.Gameplay.Combat.CombatLogic.PerformAttack(Participant instigator, Participant target) in C:\plokij\Finmer Custom\finmer\Finmer.Game\Gameplay\Combat\CombatLogic.cs:line 78
at Finmer.Gameplay.SceneCombat2.StepParticipant(Participant instigator, ECombatAction action, Participant target) in C:\plokij\Finmer Custom\finmer\Finmer.Game\Gameplay\SceneCombat2.cs:line 485
at Finmer.Gameplay.SceneCombat2.StepRound() in C:\plokij\Finmer Custom\finmer\Finmer.Game\Gameplay\SceneCombat2.cs:line 459
at Finmer.Gameplay.SceneCombat2.Turn(Int32 choice) in C:\plokij\Finmer Custom\finmer\Finmer.Game\Gameplay\SceneCombat2.cs:line 81
at Finmer.Gameplay.GameSession.ScriptThreadWorker() in C:\plokij\Finmer Custom\finmer\Finmer.Game\Gameplay\GameSession.cs:line 348
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.ThreadHelper.ThreadStart()
```

It looks as though the discrepancy between the player eating the victim and the ally killing the victim is what triggers the assert, since the line 208 in CombatSession.cs attempts to asset that the killer and predator are the same, but they are not as player is defaulted to predator

**Comment by pileofwolves** [comment]
Thanks for the report.

The core of the issue here is that autovore-prey will always be swallowed by the player character (if they are available). This leads to an incorrect assumption about the pred and killer being the same, as you already mentioned. The assert is a bug I'll need to fix regardless, but that raises an interesting question about how combat should behave in this situation...

What do you feel the correct behavior here should be? I originally intended the autovore feature to be used only in conjunction with the the player. If allies are involved, then who should be the pred? What if there is more than one ally?

I've slightly reformatted the call stack in your OP for readability, hope you don't mind.

**Comment by Wh0Kn0w5** [comment]
I think, if it be possible, that the script should first check if the ally that delivered the final blow is capable of predation. If they are, proceed with them as the predator. If they are not, run a query of all the friendly participants on the combat instance, and check if the player is there. If there is a player, then the player is the one that eats the victim. 

If there is no player involved in the combat, the remaining "allied" members should all be polled to see if they're enabled for predation, and all valid members are chosen at random to who eats the victim. In the event of no predation worthy allies, it skips the call like normal.

**Comment by pileofwolves** [comment]
I asked primarily because you mentioned earlier (in chat) that you'd like a "autovore prey for player only"-like check box. Content authors might want different things depending on the scenario:

- Player deals final blow, NPC ally should be autovore pred
- Ally deals final blow, player should be pred
- Ally deals final blow, ally should be pred

I suppose randomly selecting one if there are multiple candidate preds would work in a pinch, but I imagine it's not very useful in the common case where an author has a specific scene outcome in mind.

**Comment by Wh0Kn0w5** [comment]
Then what if there's some setting that can be called in the script.

Like how the creature can be set as an ally in the battle, maybe something to be set like "desired predator" that would take precedence over others if the intended character is still alive at the time. 

So as fas as priorities go, where the level of predators to check would be something like Preferred Pred > Killer > Player > Random ally with predation enabled.

**Comment by pileofwolves** [comment]
At first glance allowing the author to specify priorities for each of those groups - and linking specific Creatures - seems excessive. It is a lot of complexity for something the author could probably also script by hand. 

It's worth noting that the autovore feature is only meant as a convenience tool for reducing copy-pasted scripts, much like the 'has disposal scene' checkbox that you can also implement manually with a combat callback (which is how Update 1 did it).

I'm not really sure what level of support the game engine should have for this, tbh. Maybe there could be a check box for setting the player as the 'desired pred'; if they're not in the combat, autovore does nothing; if the box is unchecked, a random opposing pred is chosen instead. The more I think about it, though, the more I feel these carefully-tuned scenarios should just use scripts to accomplish their needs instead.

**Comment by Wh0Kn0w5** [comment]
Provided the documentation regarding these scenarios are sufficient for the average user to understand and apply to their own creations, sure, they can use those scripts instead.

But as far ass the assert, that will still fire unless the player is the one that triggers the final blow. Perhaps that will be the point to focus on to close this one out.
