### ISSUE TITLE
Gender radio buttons in Debug mode not applying gender correctly

### ISSUE THREAD

**Issue by Wh0Kn0w5** [pileofwolves/finmer#9]
This is another bug listed on the Trello, although it's in Backlog, so were the other issues we went over prior.

I suppose a little bit of clarification might go a long ways in what exactly this issue really is. 

- Does the gender not get saved for either option when in Debug mode, or does one in particular not get saved/saved incorrectly?
- When it happens in Debug mode, does the same thing happen in Release or whatever the term for non-debug mode is?
- Where are the values for gender saved when the character creation form validates and the user is taken to the tutorial prompt screen?

Testing again with logs shows that while the Female radio button is selected initially when starting up the game, it technically pushes the Neutral gender if no other radio button is clicked on beforehand.

Assuming based of values in the EGender script and log results.

**Comment by pileofwolves** [comment]
Okay, here's a rundown of the bug:

- When the 'basic info' page of the character creator is opened (`CharCreateBasic.CharCreateViewBase_Loaded`) we populate the UI with settings that are currently in the save data. The first time, that will all be empty, but this allows the user to later page backwards without losing data if they wish.
- The 'gender' property in save data is a value of EGender. So to see if the male button should be checked, we check whether the gender equals "Male", and set the female button to the opposite value since they are mutually exclusive (for now).
- There is no saved gender in the save data, so `InitialSaveData.GetString("gender")` returns an empty string, which of course does not equal  "Male". Therefore, the female button gets ticked. **(This is part one of the bug.)**
- The design for the page is that we initially assume the form is invalid, such as because the name field is empty whereas it shouldn't be. When the user makes changes, such as typing a name, we continually update InitialSaveData in the background with the user's latest changes and see if it now fits the requirements (`ValidateForm()`). If it does, the 'Next' button is enabled.
- Crucially, the function that runs when the gender changes and stores it in the InitialSaveData (`optGender_Checked`) will not run if the user doesn't explicitly make changes, because of the `m_Setup` flag. As you mentioned, if you change the gender at least once, this bug does not appear.
- But because the Female option is always already selected, the form is never invalid to begin with, allowing the user to skip writing the gender to InitialSaveData. **(This is part two of the bug.)**
- Later on when we get around to actually preparing a new game from the InitialSaveData, the gender property is still an empty string, and therefore defaults to Neuter (see GameObject.cs line 37). That's where the 'it' pronouns in the game log come from.

I don't think it actually has anything to do with Debug/Release modes; seems to be a mistake on my part.

Re: your last question: after validation, the gender (as part of the InitialSaveData) is passed to `GameController.BeginNewSession()`, which turns it into a Player instance.

This is the behavior I'd like to have instead:

- The game should store the gender correctly in the InitialSaveData even if the player doesn't touch the gender radio buttons at all. I'm thinking this will mean either removing or reworking the `m_Setup` thingy.
- Ideally: When the character creator is opened, and there is no stored value for gender yet, I'd like it to randomly select either (and ensure the `optGender_Checked` function runs properly so something useful is written to save data). `Finmer.Core.CoreUtility.Rng` can be used to get a random number for this purpose.

(Note: Randomizing the default gender could also be picked up later; I'm also fine to have either gender as the fixed default, as long as it works.)

**Comment by Wh0Kn0w5** [comment]
ok, as a start, I've added the check to CanGoNext to check to see if the "gender" string is null or white space, so now the CC wizard will not advance past the first part until something is selected on the radio buttons.

I currently have it so the radio buttons are both unselected, and the form is unable to progress until something is chosen. This would force the user to select an option, which would trigger the optGender_Checked function. While this would be the polar opposite of that you initially requested (have none selected instead of one automatically selected for minimal user input) I think it's a good step forward in terms of resolution.

I am not sure of an efficient way to auto-set the gender like you do with the name being "Snack" and the specie being randomly selected as of yet, but I'll keep experimenting on stuff and going from there.
